attributes = [
	'smile',
	'pure',
	'cool',
	'all',
	'elegant',
	'natural',
	'active'
	]
idols = [
	"Karin",
	"Emma",
	"Kanata",
	"Ai",
	"Kasumi",
	"Shizuku",
	"Rina",
	"Ayumu",
	"Setsuna",
	"Shioriko",
	"Hanamaru",
	"Dia",
	"Ruby",
	"Kanan",
	"Mari",
	"Riko",
	"Chika",
	"Yoshiko",
	"You",
	"Eli",
	"Rin",
	"Hanayo",
	"Honoka",
	"Kotori",
	"Maki",
	"Umi",
	"Nozomi",
	"Nico"
	]

idol_association = {
"Karin": "Asaka Karin",
"Emma": "Verde Emma",
"Kanata": "Konoe Kanata",
"Ai": "Miyashita Ai",
"Kasumi": "Nakasu Kasumi",
"Kasu": "Nakasu Kasumi",
"Shizuku": "Osaka Shizuku",
"Rina": "Tennoji Rina",
"Ayumu": "Uehara Ayumu",
"Pomu": "Uehara Ayumu",
"Setsuna": "Yuki Setsuna",
"Shioriko": "Mifune Shioriko",
"Shio": "Mifune Shioriko",
"Hanamaru": "Kunikida Hanamaru",
"Maru": "Kunikida Hanamaru",
"Zura": "Kunikida Hanamaru",
"Dia": "Kurosawa Dia",
"Ruby": "Kurosawa Ruby",
"Kanan": "Matsuura Kanan",
"Mari": "Ohara Mari",
"Riko": "Sakurauchi Riko",
"Chika": "Takami Chika",
"Yoshiko": "Tsushima Yoshiko",
"Yohane": "Tsushima Yoshiko",
"You": "Watanabe You",
"Eli": "Ayase Eli",
"Rin": "Hoshizora Rin",
"Hanayo": "Koizumi Hanayo",
"Pana": "Koizumi Hanayo",
"Honoka": "Kousaka Honoka",
"Honk": "Kousaka Honoka",
"Kotori": "Minami Kotori",
"Birb": "Minami Kotori",
"Maki": "Nishikino Maki",
"Umi": "Sonoda Umi",
"Nozomi": "Tojo Nozomi",
"Nico": "Yazawa Nico"
}

rarities={
	"R":"https://i.idol.st/static/img/i_rarity/0.png",
	"SR":"https://i.idol.st/static/img/i_rarity/1.png",
	"UR":"https://i.idol.st/static/img/i_rarity/2.png"
}